# This job deploys to a Digital Ocean droplet upon a push to the master branch or manually triggered by workflow_dispatch
name: Deploy to Digital Ocean Droplet
on:
  push:
    branches: ['main']

jobs:
  # This job runs on the latest version of ubuntu
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install --frozen-lockfile

      # Build the project using npm
      - name: Build
        run: npm run build

      # Deploy the project using SSH
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          ARGS: '-rlgoDzvc -i --delete'
          SOURCE: ''
          TARGET: '/home/h304545611/h304545611.nichost.ru/docs'
